### ISSUE TITLE
Issue displaying plaintext quotes (U+0022 ")

### ISSUE THREAD

**Issue by geoffrey-wu** [JemCasey/buzzpoints#1]
The website cuts off any text that tries to render a plain quotation mark (unicode character U+0222). For example, see this question from 2023 Chicago Open: <https://buzzpoints-5lkilhh1i-jemcasey.vercel.app/tournament/2023-chicago-open/tossup/8/9>

I'm not sure if this is an issue with how the buzzpoint migrator generates/runs the SQL statements or if it's an issue here, so I'm opening the issue here.

**Comment by JemCasey** [comment]
Thanks for catching! Pushed a fix

**Comment by geoffrey-wu** [comment]
Looks like the [fixed work](https://penn-bowl-buzzpoints-b98ce7aa3309.herokuapp.com/tournament/2023-penn-bowl-mainsite/tossup/1/14) - thanks!

**Comment by hftf** [comment]
Note to any repository issue watchers: unclear set content seems to have been spoiled in a deleted comment. Someone should kill the URL ASAP.

**Comment by geoffrey-wu** [comment]
Thanks for the heads-up - I killed the website as soon as I saw this comment, and I have relaunched it at a new URL.
